services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env
    volumes:
      - pg:/var/lib/postgres/data
  
  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env
  react:
    container_name: react
    build: ./front-end
    volumes:
      - build_react:/var/www/html 
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html 
    depends_on:
      - db
      - node_app
      - react

volumes:
  pg:
  build_react:     